sudo: false
language: go
go_import_path: e8vm.io/e8vm

go:
    - 1.5
    - tip

install:
    - go get ./...
    - go get -u e8vm.io/tools
    - go get -u github.com/golang/lint/golint

script:
    - go test ./...
    - e8chk -path="e8vm.io/e8vm"
    - golint ./...
