sudo: false
language: go
go_import_path: e8vm.io/e8vm

go:
    - 1.5

install:
    - go get ./...
    - go get -u e8vm.io/tools/cmd/e8chk
    - go get -u github.com/golang/lint/golint

script:
    - test -z `gofmt -s -l .`
    - go test ./...
    - e8chk -path="e8vm.io/e8vm"
    - golint ./...
